"""
config.py

Deployment-specific constants. Everything marked TODO below is a placeholder --
the text log has no source for these, they need to come from you / the FastCom spec.
"""
from __future__ import annotations

# --- switch / branch identity (Gcdr.dxt_id / Gcdr.provider_id) ------------------------
# TODO: confirm actual values. dxt_id is iterated byte-by-byte as hex in Gcdr.get_dxt_id,
# so if it needs to match that pattern, it should be a bytes-like sequence, not a str
# (note: Gcdr as given types dxt_id as `str` but get_dxt_id treats it as an iterable of
# ints -- that mismatch exists in the original code too; using a plain string for now
# since __iter__ just emits self.dxt_id as-is, not get_dxt_id).
DXT_ID = "ZS-DXT-ID"
PROVIDER_ID = 45

# --- output ------------------------------------------------------------------------
OUTPUT_DELIMITER = ";"  # TODO: confirm FastCom's expected column delimiter
OUTPUT_ENCODING = "utf-8"  # TODO: confirm -- Russian telecom billing imports are
                            # sometimes cp1251; the DXT log itself is UTF-16.

# --- roaming heuristic ---------------------------------------------------------------
# A call is treated as "roaming" (Dvo.rouming_dxt_id populated) when the event's
# Local Zone ID and Controlling Zone ID differ, i.e. this zone controller logged a call
# it wasn't the controller of. This is inferred from the log structure, not confirmed
# against how FastCom actually wants roaming represented -- TODO: confirm.
ROAMING_BY_ZONE_MISMATCH = True

# --- checksum ------------------------------------------------------------------------
# Gcdr.check_summ is documented as "generated by the DXT switch" -- no such value
# exists in this text log (searched the full sample, no CRC/checksum field). Self-
# computed as crc32 over the normalized row until you tell us whether FastCom actually
# validates this against a switch-provided value from elsewhere.
SELF_COMPUTE_CHECKSUM = True

# --- billing scope ---------------------------------------------------------------------
# Whether plain radio-to-radio (Individual/Group) calls should be emitted as billing
# records at all, or only PSTN-interconnected calls. TODO: confirm with the billing
# requirements -- currently set to bill everything.
BILL_RADIO_CALLS = True
